### ISSUE TITLE
Getting: Error! The command did not produce any output on windows 10

### ISSUE THREAD

**Issue by sonam185** [thiagoalessio/tesseract-ocr-for-php#155]
I have installed the thiagoalessio\TesseractOCR and it is running successfully on my system with commands:
1. echo (new TesseractOCR())->version();
2. foreach((new TesseractOCR())->availableLanguages() as $lang) echo $lang; etc 
But when I am trying to retrieve text from image it is giving the following error:
```2019-01-30 07:46:06] local.ERROR: thiagoalessio\TesseractOCR\UnsuccessfulCommandException: Error! The command did not produce any output.

Generated command:
"tesseract" "storage/ocr.png" C:\Users\test\AppData\Local\Temp\ocr78BF.tmp -l nld

Returned message:
read_params_file: Can't open test\AppData\Local\Temp\ocr78BF.tmp
read_params_file: Can't open l
read_params_file: Can't open nld
Error, could not create TXT output file: Permission denied in C:\laragon\www\ocr-scanner\vendor\thiagoalessio\tesseract_ocr\src\FriendlyErrors.php:63
Stack trace:
#0 C:\laragon\www\ocr-scanner\vendor\thiagoalessio\tesseract_ocr\src\TesseractOCR.php(24): thiagoalessio\TesseractOCR\FriendlyErrors::checkCommandExecution(Object(thiagoalessio\TesseractOCR\Command), Array)
#1 C:\laragon\www\ocr-scanner\app\Http\Controllers\OcrController.php(23): thiagoalessio\TesseractOCR\TesseractOCR->run()
#2 [internal function]: App\Http\Controllers\OcrController->read_ocr()
#3 C:\laragon\www\ocr-scanner\vendor\illuminate\container\BoundMethod.php(29): call_user_func_array(Array, Array)
#4 C:\laragon\www\ocr-scanner\vendor\illuminate\container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 C:\laragon\www\ocr-scanner\vendor\illuminate\container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#6 C:\laragon\www\ocr-scanner\vendor\illuminate\container\Container.php(572): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#7 C:\laragon\www\ocr-scanner\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(378): Illuminate\Container\Container->call(Array, Array)
#8 C:\laragon\www\ocr-scanner\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(344): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#9 C:\laragon\www\ocr-scanner\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(318): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\OcrController), 'read_ocr', Array)
#10 C:\laragon\www\ocr-scanner\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(280): Laravel\Lumen\Application->callControllerAction(Array)
#11 C:\laragon\www\ocr-scanner\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(265): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#12 C:\laragon\www\ocr-scanner\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(165): Laravel\Lumen\Application->handleFoundRoute(Array)
#13 C:\laragon\www\ocr-scanner\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(418): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Laravel\Lumen\Http\Request))
#14 C:\laragon\www\ocr-scanner\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(171): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#15 C:\laragon\www\ocr-scanner\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(108): Laravel\Lumen\Application->dispatch(NULL)
#16 C:\laragon\www\ocr-scanner\public\index.php(28): Laravel\Lumen\Application->run()
#17 {main} {"exception":"[object] (thiagoalessio\\TesseractOCR\\UnsuccessfulCommandException(code: 0): Error! The command did not produce any output.```
Please provide any solution to resolve this error. Thanks in Advance.

**Comment by thiagoalessio** [comment]
Hello @sonam185 this is happening because _apparently_ the user running your PHP script has no write permissions to ``.

I just happened to release version `2.7.3` to address a similar issue. This wrapper now allows you to set a custom temporary directory for tesseract. https://github.com/thiagoalessio/tesseract-ocr-for-php#tempdir

Please let me know if that solves your issue.

**Comment by thiagoalessio** [comment]
closing this issue for now. please feel free to reopen it if the new version didn't solve the problem.
